/**
 * @file
 * This header file declares the function to create one instance of the CrPsCmdPrgrSucc procedure.
 * The procedure is configured with a set of function pointers representing the non-default
 * actions and guards of the procedure. Some of these functions may also be declared in
 * this header file in accordance with the configuration of the procedure in the FW Profile
 * Editor. In the latter case, the user has to provide an implementation for these functions
 * in a user-supplied body file.
 *
 * This header file has been automatically generated by the FW Profile Editor.
 * The procedure created by this file is shown in the figure below.
 * @image html CrPsCmdPrgrSucc.png
 *
 * @author FW Profile code generator version 5.01
 * @date Created on: Jul 11 2017 17:59:40
 */

/** Make sure to include this header file only once */
#ifndef CRPSCMDPRGRSUCC_H_
#define CRPSCMDPRGRSUCC_H_

/** FW Profile function definitions */
#include "FwPrConstants.h"

/** Action node identifiers */
#define CrPsCmdPrgrSucc_N2 (1)		/* The identifier of action node N2 in procedure CrPsCmdPrgrSucc */
#define CrPsCmdPrgrSucc_N3 (2)		/* The identifier of action node N3 in procedure CrPsCmdPrgrSucc */
#define CrPsCmdPrgrSucc_N4 (3)		/* The identifier of action node N4 in procedure CrPsCmdPrgrSucc */

/**
 * Create a new procedure descriptor.
 * This interface creates the procedure descriptor dynamically.
 * @param prData the pointer to the procedure data.
 * A value of NULL is legal (note that the default value of the pointer
 * to the procedure data when the procedure is created is NULL).
 * @return the pointer to the procedure descriptor
 */
FwPrDesc_t CrPsCmdPrgrSuccCreate(void* prData);

/* Action for node N2. */
void CrPsCmdPrgrSuccN2(FwPrDesc_t __attribute__((unused)) prDesc);

/* Action for node N3. */
void CrPsCmdPrgrSuccN3(FwPrDesc_t __attribute__((unused)) prDesc);

/* Action for node N4. */
void CrPsCmdPrgrSuccN4(FwPrDesc_t __attribute__((unused)) prDesc);

/* Guard on the Control Flow from DECISION1 to N3. */
FwPrBool_t CrPsCmdPrgrSuccG1(FwPrDesc_t __attribute__((unused)) prDesc);

#endif /* CrPsCmdPrgrSuccCreate_H_ */
