/**
 * @file
 * This header file declares the function to create one instance of the CrPsCmdPrgrFail procedure.
 * The procedure is configured with a set of function pointers representing the non-default
 * actions and guards of the procedure. Some of these functions may also be declared in
 * this header file in accordance with the configuration of the procedure in the FW Profile
 * Editor. In the latter case, the user has to provide an implementation for these functions
 * in a user-supplied body file.
 *
 * This header file has been automatically generated by the FW Profile Editor.
 * The procedure created by this file is shown in the figure below.
 * @image html CrPsCmdPrgrFail.png
 *
 * @author FW Profile code generator version 5.01
 * @date Created on: Jul 11 2017 17:58:12
 */

/** Make sure to include this header file only once */
#ifndef CRPSCMDPRGRFAIL_H_
#define CRPSCMDPRGRFAIL_H_

/** FW Profile function definitions */
#include "FwPrConstants.h"

/** Action node identifiers */
#define CrPsCmdPrgrFail_N2 (1)		/* The identifier of action node N2 in procedure CrPsCmdPrgrFail */
#define CrPsCmdPrgrFail_N3 (2)		/* The identifier of action node N3 in procedure CrPsCmdPrgrFail */
#define CrPsCmdPrgrFail_N4 (3)		/* The identifier of action node N4 in procedure CrPsCmdPrgrFail */
#define CrPsCmdPrgrFail_N5 (4)		/* The identifier of action node N5 in procedure CrPsCmdPrgrFail */
#define CrPsCmdPrgrFail_N6 (5)		/* The identifier of action node N6 in procedure CrPsCmdPrgrFail */

/**
 * Create a new procedure descriptor.
 * This interface creates the procedure descriptor dynamically.
 * @param prData the pointer to the procedure data.
 * A value of NULL is legal (note that the default value of the pointer
 * to the procedure data when the procedure is created is NULL).
 * @return the pointer to the procedure descriptor
 */
FwPrDesc_t CrPsCmdPrgrFailCreate(void* prData);

/* Action for node N2. */
void CrPsCmdPrgrFailN2(FwPrDesc_t __attribute__((unused)) prDesc);

/* Action for node N3. */
void CrPsCmdPrgrFailN3(FwPrDesc_t __attribute__((unused)) prDesc);

/* Action for node N4. */
void CrPsCmdPrgrFailN4(FwPrDesc_t __attribute__((unused)) prDesc);

/* Action for node N5. */
void CrPsCmdPrgrFailN5(FwPrDesc_t __attribute__((unused)) prDesc);

/* Action for node N6. */
void CrPsCmdPrgrFailN6(FwPrDesc_t __attribute__((unused)) prDesc);

/* Guard on the Control Flow from DECISION1 to N3. */
FwPrBool_t CrPsCmdPrgrFailG1(FwPrDesc_t __attribute__((unused)) prDesc);

#endif /* CrPsCmdPrgrFailCreate_H_ */
