/**
 * @file CrPsRepErr.c
 * @ingroup PUSTestsuite
 * @ingroup PUSTestconfig
 *
 * @brief Implementation of the PUS extension error reporting interface for the Test Application.
 *
 * \see CrFwRepErr.h
 *
 * This implementation writes the error reports to standard output.
 *
 * @authors V. Cechticky and A. Pasetti
 * @copyright P&P Software GmbH, 2014
 *
 * @author Christian Reimers <christian.reimers@univie.ac.at>
 * @author Markus Rockenbauer <markus.rockenbauer@univie.ac.at>
 *
 * last modification: 22.01.2018
 *
 * @copyright P&P Software GmbH, 2015 / Department of Astrophysics, University of Vienna, 2018
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* Include Framework Files */
#include "CrFwConstants.h"
#include "CrPsRepErr.h"
#include <CrPsUtilitiesServReqVerif.h>

/*-----------------------------------------------------------------------------------------*/
void CrPsRepErr(CrPsRepErrCode_t errCode, CrFwServType_t tmtcType, CrFwServSubType_t tmtcSubType, CrFwDiscriminant_t tmtcDiscriminant)
{
	CRFW_UNUSED(tmtcType);
	CRFW_UNUSED(tmtcSubType);
	CRFW_UNUSED(tmtcDiscriminant);

  switch (errCode)
  {
    case crOutfactoryFail:
      /*printf("CrPsErrRep: error OUTFACTORY_FAIL generated by component (%d,%d,%d)\n", tmtcType,tmtcSubType, tmtcDiscriminant);*/
      break;

    default:
      /*printf("CrPsErrRep: error %d generated by component (%d,%d,%d)\n", errCode,tmtcType,tmtcSubType, tmtcDiscriminant);*/
      break;
  }
  
  return;
}

/*-----------------------------------------------------------------------------------------*/

void CrFwRepErrInstanceIdAndDest(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId,
                                 CrFwInstanceId_t instanceId, CrFwInstanceId_t secondaryInstanceId, CrFwDestSrc_t dest)
{

  /*printf("CrFwRepErrInstanceIdAndDest: error %d generated by component %d of type %d\n",errCode,instanceId,typeId);*/
  /*printf("                             secondary sequence identifier: %d, destination: %d\n",secondaryInstanceId,dest);*/

	CRFW_UNUSED(typeId);
	CRFW_UNUSED(instanceId);
	CRFW_UNUSED(secondaryInstanceId);
	CRFW_UNUSED(dest);

  switch (errCode)
  {
    case crInLoaderInvDest:
      /*printf("CrFwRepErrInstanceIdAndDest: crInLoaderInvDest\n");*/
      SendReqVerifPcktReroutFailRep(NULL, INLOADER_INV_DEST); /* TODO: NULL have to be changed to smDesc of in-coming packet */
      break;

    default:
      break;
  }

  return;
}
