/**
 * @file CrPsRepErr.c
 * @ingroup 
 *
 * Implementation of the PUS extension error reporting interface for the Test
 * Application.
 *
 * \see CrFwRepErr.h
 *
 * This implementation writes the error reports to standard output.
 *
 * @authors V. Cechticky and A. Pasetti
 * @copyright P&P Software GmbH, 2014
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* Include Framework Files */
#include "CrFwConstants.h"
#include "CrPsRepErr.h"

/*-----------------------------------------------------------------------------------------*/
void CrPsRepErr(CrPsRepErrCode_t errCode, CrFwServType_t tmtcType, CrFwServSubType_t tmtcSubType, CrFwDiscriminant_t tmtcDiscriminant)
{

  switch (errCode)
  {
    case crOutfactoryFail:
      printf("CrFwErrRep: error OUTFACTORY_FAIL generated by component (%d,%d,%d)\n", tmtcType,tmtcSubType, tmtcDiscriminant);
      break;

    default:
      printf("CrFwErrRep: error %d generated by component (%d,%d,%d)\n", errCode,tmtcType,tmtcSubType, tmtcDiscriminant);
      break;
  }
  
  return;
}
