/**
 * @file CrPsRepErr.c
 * @ingroup 
 *
 * Implementation of the PUS extension error reporting interface for the Test
 * Application.
 *
 * \see CrFwRepErr.h
 *
 * This implementation writes the error reports to standard output.
 *
 * @authors V. Cechticky and A. Pasetti
 * @copyright P&P Software GmbH, 2014
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* Include Framework Files */
#include "CrFwConstants.h"
#include "CrPsRepErr.h"
#include <CrPsUtilities.h>

/*-----------------------------------------------------------------------------------------*/
void CrPsRepErr(CrPsRepErrCode_t errCode, CrFwServType_t tmtcType, CrFwServSubType_t tmtcSubType, CrFwDiscriminant_t tmtcDiscriminant)
{

  switch (errCode)
  {
    case crOutfactoryFail:
      printf("CrFwErrRep: error OUTFACTORY_FAIL generated by component (%d,%d,%d)\n", tmtcType,tmtcSubType, tmtcDiscriminant);
      break;

    default:
      printf("CrFwErrRep: error %d generated by component (%d,%d,%d)\n", errCode,tmtcType,tmtcSubType, tmtcDiscriminant);
      break;
  }
  
  return;
}

/*-----------------------------------------------------------------------------------------*/

void CrFwRepErrInstanceIdAndDest(CrFwRepErrCode_t errCode, CrFwTypeId_t typeId,
                                 CrFwInstanceId_t instanceId, CrFwInstanceId_t secondaryInstanceId, CrFwDestSrc_t dest)
{
  printf("CrFwRepErrInstanceIdAndDest: error %d generated by component %d of type %d\n",errCode,instanceId,typeId);
  printf("                             secondary sequence identifier: %d, destination: %d\n",secondaryInstanceId,dest);

  switch (errCode)
  {
    case crInLoaderInvDest:
      printf("CrFwRepErrInstanceIdAndDest: crInLoaderInvDest\n");
      SendReqVerifPcktReroutFailRep(NULL, INLOADER_INV_DEST); /* TODO: NULL have to be changed to smDesc of in-coming packet */
      break;

    default:
      break;
  }

  return;
}


