name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone fwprofile
      run: git clone https://github.com/pnp-software/fwprofile.git ./lib/fwprofile


    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpthread-stubs0-dev

    - name: Build project
      run: |
        make